name: wifi_connector
description: Flutter plug-in for connecting to wifi.
version: 2.0.0
homepage: https://wonjerry.github.io/
repository: https://github.com/wonjerry/flutter_wifi_connector

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.wonjerry.wifi_connector
        pluginClass: WifiConnectorPlugin
      ios:
        pluginClass: WifiConnectorPlugin
